from datetime import datetime, timezone
import logging
import uuid
from typing import Optional

from sqlalchemy.orm import Session

from crawler.models.source import Source
from crawler.models.crawler_run import CrawlerRun
from crawler.models.raw_record import RawRecord

from crawler.collectors.registry import CollectorRegistry
from crawler.collectors.transport import (
    DirectHTTPTransport,
    TorProxyTransport,
)

from crawler.policy.robots_checker import RobotsChecker
from crawler.policy.rate_limiter import RateLimiter

from crawler.keywords.service import KeywordService

from crawler.pipeline.cleaner import ContentCleaner
from crawler.pipeline.dedup import Deduplicator
from crawler.pipeline.language import LanguageDetector
from crawler.pipeline.relevance_filter import KeywordMatcher
from crawler.pipeline.relevance_classifier import LLMRelevanceClassifier
from crawler.pipeline.entity_extractor import EntityExtractor

from crawler.evidence.tagging import EvidenceTagger

from crawler.recovery.engine import RecoveryEngine

from services.detection_pipeline import process_raw_records


logger = logging.getLogger(__name__)

extractor = EntityExtractor()


async def run_crawl(
    source_id: str,
    case_id: Optional[str] = None,
    triggered_by: Optional[int] = None,
    db: Optional[Session] = None,
) -> CrawlerRun:
    """
    Executes an end-to-end crawler pipeline flow parameterized by
    (source_id, case_id).

    Pipeline:

        Collector
            ↓
        Raw artifact
            ↓
        Evidence tagging + original SHA-256
            ↓
        Deduplication
            ↓
        Content recovery
            ↓
        Content cleaning
            ↓
        Language detection
            ↓
        Keyword filtering
            ↓
        Entity / IOC extraction
            ↓
        AI relevance classification
            ↓
        RawRecord persistence
            ↓
        Detection pipeline

    Important evidence guarantees:

        raw_text:
            Always contains the original fetched artifact.

        content_hash:
            SHA-256 of the original raw_text.

        recovered_text:
            Derived content produced by the recovery engine.

        recovery_metadata:
            Structured explanation of what the recovery engine
            detected and/or recovered.
    """

    if db is None:
        from database import SessionLocal

        db = SessionLocal()
        should_close_db = True
    else:
        should_close_db = False

    # ------------------------------------------------------------------
    # 1. Create crawler run
    # ------------------------------------------------------------------

    run = CrawlerRun(
        id=uuid.uuid4(),
        source_id=(
            uuid.UUID(str(source_id))
            if isinstance(source_id, str)
            else source_id
        ),
        case_id=case_id,
        status="RUNNING",
        started_at=datetime.now(timezone.utc),
        triggered_by=triggered_by,
    )

    db.add(run)
    db.commit()

    try:
        # ------------------------------------------------------------------
        # 2. Resolve source and active keywords
        # ------------------------------------------------------------------

        source = (
            db.query(Source)
            .filter(Source.id == run.source_id)
            .first()
        )

        if not source:
            run.status = "FAILED"
            run.error_summary = (
                f"Source with ID {source_id} not found."
            )
            run.finished_at = datetime.now(timezone.utc)

            db.commit()
            return run

        active_keywords = KeywordService.get_active_keywords(
            db,
            case_id=case_id,
        )

        source_config = dict(source.config or {})
        source_config["keywords"] = active_keywords

        # ------------------------------------------------------------------
        # 3. Instantiate collector and transport
        # ------------------------------------------------------------------

        collector = CollectorRegistry.get_collector(
            source.source_type
        )

        if source.transport_type == "tor_proxy":
            transport = TorProxyTransport()
        else:
            transport = DirectHTTPTransport()

        # ------------------------------------------------------------------
        # 4. Fetch raw records
        # ------------------------------------------------------------------

        fetched_records = await collector.fetch(
            source_config,
            transport,
        )

        # Persist recursive discovery state generated by collector.
        source.config = source_config

        run.urls_attempted = len(fetched_records)

        db.commit()

        robots_checker = RobotsChecker()

        rate_limiter = RateLimiter(
            default_delay=float(
                source.crawl_delay_seconds or 1.0
            )
        )

        classifier = LLMRelevanceClassifier()

        # ------------------------------------------------------------------
        # 5. Process each fetched record
        # ------------------------------------------------------------------

        for rec in fetched_records:

            # --------------------------------------------------------------
            # Refresh state so stop requests are noticed.
            # --------------------------------------------------------------

            db.refresh(source)
            db.refresh(run)

            if run.status == "STOPPED" or not source.is_active:
                run.status = "STOPPED"
                run.finished_at = datetime.now(timezone.utc)
                run.error_summary = (
                    "Crawl stopped by operator."
                )

                db.commit()
                return run

            url = rec.get("url")

            if not url:
                continue

            # --------------------------------------------------------------
            # Robots policy
            # --------------------------------------------------------------

            allowed = await robots_checker.is_allowed(
                url=url,
                user_agent="DarkKnightCrawler/1.0",
                db=db,
                transport=transport,
            )

            if not allowed:
                run.urls_skipped_robots += 1
                db.commit()
                continue

            # --------------------------------------------------------------
            # Rate limiting
            # --------------------------------------------------------------

            await rate_limiter.wait_if_needed(
                url,
                requested_delay=float(
                    source.crawl_delay_seconds or 1.0
                ),
            )

            # --------------------------------------------------------------
            # Evidence tagging
            #
            # This MUST occur before recovery.
            #
            # content_hash represents the original fetched artifact.
            # --------------------------------------------------------------

            try:
                rec_tagged = EvidenceTagger.tag_and_validate(
                    rec,
                    run_id=run.id,
                )

            except ValueError as ve:
                logger.error(
                    f"Provenance validation error for {url}: {ve}"
                )

                run.errors_count += 1
                db.commit()
                continue

            content_hash = rec_tagged["content_hash"]

            # --------------------------------------------------------------
            # Deduplication
            #
            # Always based on the original artifact.
            # --------------------------------------------------------------

            if Deduplicator.is_duplicate(
                content_hash,
                db,
            ):
                logger.info(
                    f"Duplicate content hash {content_hash} "
                    f"for {url}, skipping."
                )
                continue

            # --------------------------------------------------------------
            # Original raw content
            # --------------------------------------------------------------

            raw_text = (
                rec_tagged.get("raw_text", "")
                or ""
            )

            # --------------------------------------------------------------
            # Recovery
            # --------------------------------------------------------------
            #
            # The recovery layer gets the raw artifact but does not modify
            # raw_text or content_hash.
            # --------------------------------------------------------------

            try:
                recovery_result = RecoveryEngine.process(
                    raw_text
                )

            except Exception as recovery_exc:
                # Recovery failure must not kill the crawler.
                logger.warning(
                    f"Recovery processing failed for {url}: "
                    f"{recovery_exc}",
                    exc_info=True,
                )

                recovery_result = None

            # --------------------------------------------------------------
            # Determine downstream processing content
            # --------------------------------------------------------------

            if (
                recovery_result is not None
                and recovery_result.recovered
                and recovery_result.recovered_content
            ):
                processing_text = (
                    recovery_result.recovered_content
                )
                recovered_text = (
                    recovery_result.recovered_content
                )
            else:
                processing_text = raw_text
                recovered_text = None

            # --------------------------------------------------------------
            # Recovery metadata
            # --------------------------------------------------------------

            if recovery_result is not None:
                recovery_metadata = (
                    recovery_result.to_dict()
                )

                # raw_text is already stored independently as original
                # evidence, so avoid duplicating it inside JSON metadata.
                recovery_metadata.pop(
                    "original_content",
                    None,
                )

            else:
                recovery_metadata = {
                    "status": "recovery_error",
                    "recovered": False,
                    "confidence": 0.0,
                    "transformations": [],
                    "candidates_considered": [],
                    "error": "Recovery engine failed.",
                }

            # --------------------------------------------------------------
            # Content cleaning
            # --------------------------------------------------------------

            cleaned_text = ContentCleaner.clean(
                processing_text
            )

            # --------------------------------------------------------------
            # Language detection
            # --------------------------------------------------------------

            lang = LanguageDetector.detect(
                cleaned_text
            )

            # --------------------------------------------------------------
            # Keyword pre-filter
            # --------------------------------------------------------------

            matched_kws, is_passed = KeywordMatcher.match(
                cleaned_text,
                active_keywords,
            )

            # --------------------------------------------------------------
            # Discarded by keyword filter
            # --------------------------------------------------------------

            if not is_passed:
                raw_rec = RawRecord(
                    run_id=run.id,
                    source_id=source.id,
                    case_id=case_id,
                    url=url,
                    fetched_at=rec_tagged["fetched_at"],

                    # Original evidence
                    raw_text=raw_text,

                    # Derived content
                    recovered_text=recovered_text,
                    recovery_metadata=recovery_metadata,
                    cleaned_text=cleaned_text,

                    # Original evidence hash
                    content_hash=content_hash,

                    language=lang,
                    matched_keywords=[],
                    relevance_label="unrelated",
                    relevance_confidence=1.0,
                    relevance_reasoning=(
                        "No active keywords matched."
                    ),
                    extracted_candidates=[],
                    status="discarded",
                )

                db.add(raw_rec)

                run.records_produced += 1

                db.commit()

                process_raw_records(
                    db,
                    [raw_rec.id],
                )

                continue

            # --------------------------------------------------------------
            # Entity extraction / IOC extraction
            #
            # Uses recovered content when recovery succeeded.
            # --------------------------------------------------------------

            candidates = extractor.extract(
                cleaned_text
            )

            # --------------------------------------------------------------
            # AI relevance classification
            # --------------------------------------------------------------

            rel_result = await classifier.classify(
                cleaned_text,
                matched_kws,
                candidates,
            )

            logger.info(
                f"LLM structured intelligence for {url}: "
                f"{rel_result.structured_intelligence}"
            )

            # --------------------------------------------------------------
            # Determine routing status
            # --------------------------------------------------------------

            if rel_result.label == "relevant":
                status_val = "pending_mapping"
                run.records_relevant += 1

            elif (
                rel_result.confidence < 0.8
                or rel_result.label == "medical_legitimate"
            ):
                status_val = "review_queue"

            else:
                status_val = "discarded"

            # --------------------------------------------------------------
            # Persist RawRecord
            # --------------------------------------------------------------

            raw_rec = RawRecord(
                run_id=run.id,
                source_id=source.id,
                case_id=case_id,
                url=url,
                fetched_at=rec_tagged["fetched_at"],

                # Original evidence
                raw_text=raw_text,

                # Derived recovery information
                recovered_text=recovered_text,
                recovery_metadata=recovery_metadata,

                # Derived cleaned content
                cleaned_text=cleaned_text,

                # Original evidence hash
                content_hash=content_hash,

                language=lang,
                matched_keywords=matched_kws,
                relevance_label=rel_result.label,
                relevance_confidence=rel_result.confidence,
                relevance_reasoning=rel_result.reasoning,
                extracted_candidates=candidates,
                structured_intelligence=(
                    rel_result.structured_intelligence
                ),
                status=status_val,
            )

            db.add(raw_rec)

            run.records_produced += 1

            # Commit after each record so the frontend can see activity
            # while the crawl is running.
            db.commit()

            process_raw_records(
                db,
                [raw_rec.id],
            )

        # ------------------------------------------------------------------
        # 6. Crawl completed
        # ------------------------------------------------------------------

        run.status = "COMPLETED"
        run.finished_at = datetime.now(timezone.utc)

        db.commit()

    except Exception as exc:
        db.rollback()

        run.status = "FAILED"
        run.error_summary = str(exc)
        run.finished_at = datetime.now(timezone.utc)

        db.commit()

        logger.error(
            f"Crawler run failed: {exc}",
            exc_info=True,
        )

    finally:
        if should_close_db:
            db.close()

    return run